// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApdII0E98rjIXbUDTQzLRdS-ETsqNJ_UU',
    appId: '1:201578437650:web:9832fab01d150f02f84ccb',
    messagingSenderId: '201578437650',
    projectId: 'kawamen-f1098',
    authDomain: 'kawamen-f1098.firebaseapp.com',
    storageBucket: 'kawamen-f1098.firebasestorage.app',
    measurementId: 'G-54TMHHMG78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQ2_Xjm7brlTCDSONbCJtKaZW6PscZzU',
    appId: '1:201578437650:android:3e113b5051e07be2f84ccb',
    messagingSenderId: '201578437650',
    projectId: 'kawamen-f1098',
    storageBucket: 'kawamen-f1098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXglmcHXLhi_tZ95WDJ9KJ0HbktLxRUY',
    appId: '1:201578437650:ios:01c7d125fee4297af84ccb',
    messagingSenderId: '201578437650',
    projectId: 'kawamen-f1098',
    storageBucket: 'kawamen-f1098.firebasestorage.app',
    iosBundleId: 'com.kawamen.android',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXglmcHXLhi_tZ95WDJ9KJ0HbktLxRUY',
    appId: '1:201578437650:ios:01c7d125fee4297af84ccb',
    messagingSenderId: '201578437650',
    projectId: 'kawamen-f1098',
    storageBucket: 'kawamen-f1098.firebasestorage.app',
    iosBundleId: 'com.kawamen.android',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApdII0E98rjIXbUDTQzLRdS-ETsqNJ_UU',
    appId: '1:201578437650:web:991ceef8cb48a406f84ccb',
    messagingSenderId: '201578437650',
    projectId: 'kawamen-f1098',
    authDomain: 'kawamen-f1098.firebaseapp.com',
    storageBucket: 'kawamen-f1098.firebasestorage.app',
    measurementId: 'G-DKSXT1YH21',
  );
}
